.TH akkiu 1 "Sun 05 Mar 2023 02:50:40 PM MSK" "v0.0.1" "akkiu man page"
.SH NAME
akkiu - learn boring things in console
.SH SYNOPSIS
akkiu [MODE] [FILE]
.SH DESCRIPTION
nuseradd is high level shell program for adding users to LDAP server.  On Debian, administrators should usually use nuseradd.debian(8) instead.
.SH MODE
[ --help | help | -h ] - show this message

[ --poem | poem | -p ] - launch in poem mode

[ --words | words | -w ] - launch in words mode

.SH SEE ALSO
cat(1)
.SH BUGS
No known bugs. If found, please report bugs to https://github.com/mb6ockatf/akktiu/issues
.SH AUTHOR
@mb6ockatf https://github.com/mb6ockatf
